# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: tmp3
services:
  kafka:
    extends:
      file: ./kafka.yml
      service: kafka
